### ISSUE TITLE
LiveChessCloud - No Round tag export

### ISSUE THREAD

**Issue by gmvlasta** [ecrucru/boards#2]
Hi,
downloading pgn from LiveChessCloud.com does not export Round tag. Sometimes there is also Board indicated, so it could be useful to export both together as one Round tag (for example Round 3, Board 5 as Round 3.5).

**Comment by ecrucru** [comment]
Hello @gmvlasta

The requested feature is added but remains imprecise (incremental counters).
If you have a counter example, feel free to share its link to improve the analysis.

Chess960 is also added.

Thanks for your feedback.

**Comment by gmvlasta** [comment]
Dear friend,

thank you very much for adding the feature. I don't understand the
remark about counter, for my links it works as expected, for example

https://view.livechesscloud.com/#64ee1d6d-7873-424b-bbbc-46775c6e978b
https://view.livechesscloud.com/#8c2409d5-71fa-448f-b590-b362ad2e4a50

Nevertheless, I have another request as well. The site

http://online.chessfm.cz/TSN22/TSN/index.html

looks very much like LiveChessCloud but it is a bit different. Would
it be possible to add support also for such sites? Thanks.

Regards,

gmvlasta


V Fri, 24 Feb 2023 17:36:16 -0800
ecrucru ***@***.***> napsáno:

> Hello @gmvlasta
> 
> The requested feature is added but remains imprecise (incremental
> counters). If you have a counter example, feel free to share its link
> to improve the analysis.
> 
> Chess960 is also added.
> 
> Thanks for your feedback.
>

**Comment by ecrucru** [comment]
Hello @gmvlasta 

Custom LiveChess instances are not supported yet. In the meanwhile, you can use/adapt the following script:

```python
from lib.bp_interface import InternetGameInterface
buffer = ''
dlh = InternetGameInterface()
for R in range(9):
    for B in range(9):
        url = 'http://online.chessfm.cz/TSN22/TSN/round-%d/game-%d.pgn' % (R + 1, B + 1)
        buffer += dlh.download(url) + '\n\n'
print(buffer)
```

```sh
python3 file_above.py > output.pgn
```

Your request is now completed !

**Comment by gmvlasta** [comment]
Dear friend,

thank you for your script, it works well. After sending my email and
looking at details, I also realized that is possible just simply
collect individual pgn files that way you do in the script.

Regards,

gmvlasta


V Mon, 27 Feb 2023 16:00:55 -0800
ecrucru ***@***.***> napsáno:

> Hello @gmvlasta 
> 
> Custom LiveChess instances are not supported yet. In the meanwhile,
> you can use/adapt the following script:
> 
> ```python
> from lib.bp_interface import InternetGameInterface
> buffer = ''
> dlh = InternetGameInterface()
> for R in range(9):
>     for B in range(9):
>         url =
> 'http://online.chessfm.cz/TSN22/TSN/round-%d/game-%d.pgn' % (R + 1, B
> + 1) buffer += dlh.download(url) + '\n\n' print(buffer)
> ```
> 
> ```sh
> python3 file_above.py > output.pgn
> ```
> 
> Your request is now completed !
>
